name: Build on ARM64

on:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: actuated-aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S base-devel --noconfirm

      - name: Build project
        run: |
          make
