name: ARM64 Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: actuated-arm64-4cpu
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: sudo apt update && sudo apt install -y build-essential
      - name: Run build script
        run: ./build.sh

- name: Run tests
  run: ./test.sh

- name: Upload build output
  uses: actions/upload-artifact@v3
  with:
    name: binaries
    path: ./bin/
